name: Production Database Update 🛠️

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ollix-api
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  database-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Restore
        run: dotnet restore ./ollix-backend.sln
      - name: Update Database
        run: |
          cd ollix-backend\src\Ollix.Infrastructure.Data
          dotnet ef database update --context AppDbContext --startup-project ../Ollix.Infrastructure.IoC
        env:
          DefaultConnection: ${{ secrets.DbConnectionString }}
